import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

final kHeight5 = SizedBox(height: 5.h);
final kHeight10 = SizedBox(height: 10.h);
final kHeight15 = SizedBox(height: 15.h);
final kHeight20 = SizedBox(height: 20.h);
final kHeight25 = SizedBox(height: 25.h);
final kHeight30 = SizedBox(height: 30.h);
final kHeight35 = SizedBox(height: 35.h);
final kHeight40 = SizedBox(height: 40.h);
final kHeight45 = SizedBox(height: 45.h);
final kHeight50 = SizedBox(height: 50.h);
final kHeight55 = SizedBox(height: 55.h);
final kHeight60 = SizedBox(height: 60.h);
final kHeight65 = SizedBox(height: 65.h);
final kHeight70 = SizedBox(height: 70.h);
final kHeight75 = SizedBox(height: 75.h);
final kHeight80 = SizedBox(height: 80.h);
final kHeight85 = SizedBox(height: 85.h);
final kHeight90 = SizedBox(height: 90.h);
final kHeight95 = SizedBox(height: 95.h);
final kHeight100 = SizedBox(height: 100.h);

final kWidth5 = SizedBox(width: 5.w);
final kWidth10 = SizedBox(width: 10.w);
final kWidth15 = SizedBox(width: 15.w);
final kWidth20 = SizedBox(width: 20.w);
final kWidth25 = SizedBox(width: 25.w);
final kWidth30 = SizedBox(width: 30.w);
final kWidth35 = SizedBox(width: 35.w);
final kWidth40 = SizedBox(width: 40.w);
final kWidth45 = SizedBox(width: 45.w);
final kWidth50 = SizedBox(width: 50.w);
final kWidth55 = SizedBox(width: 55.w);
final kWidth60 = SizedBox(width: 60.w);
final kWidth65 = SizedBox(width: 65.w);
final kWidth70 = SizedBox(width: 70.w);
final kWidth75 = SizedBox(width: 75.w);
final kWidth80 = SizedBox(width: 80.w);
final kWidth85 = SizedBox(width: 85.w);
final kWidth90 = SizedBox(width: 90.w);
final kWidth95 = SizedBox(width: 95.w);
final kWidth100 = SizedBox(width: 100.w);